### ISSUE TITLE
多卡运行，分布式训练

### ISSUE THREAD

**Issue by Lmy0914** [Yuan-Yutao/ECDP#1]
作者你好，代码可以用多张显卡分布式训练吗？ecdp-df2k-train.yaml 配置文件里的 distributed: 改为true 之后，在 train ECDP 时会报错：
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/img/anaconda3/envs/ECDP/lib/python3.10/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/home/img/anaconda3/envs/ECDP/lib/python3.10/multiprocessing/spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
  File "/media/img/samsung//projects/ECDP//lib/options.py", line 40, in __getattr__
    return self._items[name]
  File "/media/img/samsung//projects/ECDP//lib/options.py", line 40, in __getattr__
    return self._items[name]
  File "/media/img/samsung//projects/ECDP//lib/options.py", line 40, in __getattr__
    return self._items[name]
  [Previous line repeated 993 more times]
RecursionError: maximum recursion depth exceeded
以及
torch.multiprocessing.spawn.ProcessExitedException: process 0 terminated with exit code 1

**Comment by Yuan-Yutao** [comment]
代码里面多卡训练的部分是其他项目里面留下来的，在这个项目里面没有测试过

**Comment by Lmy0914** [comment]
好的谢谢！
